version: '3'
services:
  our-blog:
    image: kaelsihombing/our-blog:latest
    container_name: "our-blog"
    network_mode: "host"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DB_CONNECTION_PRODUCTION=mongodb://localhost/our-blog_production 
      - secretKey='Hello World!'
      - publicKey="u+m9pCNymW3XCt/A9VTTXzp7J/k="
      - privateKey="CizqMnPgwlfXuRe7b6LXnmPf7LY="
      - urlEndpoint="latihan"
      - API_KEY_DALLAH="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"
      - BASE_URL="http://localhost:5000"
